import { library } from '@fortawesome/fontawesome-svg-core';

import {
	farQrCode as farcQrCode,
	farPositionReplacement as farcPositionReplacement,
	farPositionDetach as farcPositionDetach,
	falReceiptsMissing as falcReceiptsMissing,
} from './fontAwecomeCustomIcons';

import { faVk, faInstagram } from '@fortawesome/free-brands-svg-icons';

import {
	faAngleLeft as fasAngleLeft,
	faAngleRight as fasAngleRight,
	faAngleUp as fasAngleUp,
	faAngleDown as fasAngleDown,
	faHeart as fasHeart,
	faComment as fasComment,
	faBullhorn as fasBullhorn,
	faUserAlt as fasUserAlt,
	faCheckSquare as fasCheckSquare,
	faWallet as fasWallet,
	faPen as fasPen,
	faCircle as fasCircle,
	faClock as fasClock,
	faRubleSign as fasRubleSign,
	faCheckCircle as fasCheckCircle,
	faQuestionCircle as fasQuestionCircle,
	faExclamationCircle as fasExclamationCircle,
	faStore as fasStore,
} from '@fortawesome/pro-solid-svg-icons';

import {
	faAngleLeft as farAngleLeft,
	faAngleRight as farAngleRight,
	faAngleUp as farAngleUp,
	faAngleDown as farAngleDown,
	faTimes as farTimes,
	faCalendar as farCalendar,
	faClipboard as farClipboard,
	faTrashAlt as farTrashAlt,
	faEye as farEye,
	faClone as farClone,
	faEllipsisH as farEllipsisH,
	faEllipsisV as farEllipsisV,
	faCheck as farCheck,
	faCircle as farCircle,
	faDotCircle as farDotCircle,
	faSyncAlt as farSyncAlt,
	faPlus as farPlus,
	faSquare as farSquare,
	faExclamationCircle as farExclamationCircle,
	faChevronDown as farChevronDown,
	faChevronUp as farChevronUp,
	faUndo as farUndo,
	faArchive as farArchive,
	faBoxAlt as farBoxAlt,
	faPen as farPen,
	faFolderPlus as farFolderPlus,
	faFolderMinus as farFolderMinus,
	faTruck as farTruck,
	faCog as farCog,
	faTruckLoading as farTruckLoading,
	faCalendarEdit as farCalendarEdit,
	faTrash as farTrash,
	faComment as farComment,
	faInventory as farInventory,
	faExternalLink as farExternalLink,
} from '@fortawesome/pro-regular-svg-icons';

import {
	faAngleLeft as falAngleLeft,
	faAngleRight as falAngleRight,
	faAngleUp as falAngleUp,
	faAngleDown as falAngleDown,
	faTimes as falTimes,
	faTimesCircle as falTimesCircle,
	faQuestionCircle as falQuestionCircle,
	faExclamationCircle as falExclamationCircle,
	faVideo as falVideo,
	faPlus as falPlus,
	faClipboardListCheck as falClipboardListCheck,
	faCheckCircle as falCheckCircle,
	faPlusCircle as falPlusCircle,
	faShippingTimed as falShippingTimed,
	faShoppingCart as falShoppingCart,
	faBagsShopping as falBagsShopping,
	faExternalLinkSquare as falExternalLinkSquare,
	faUndo as falUndo,
	faUsers as falUsers,
	faTachometer as falTachometer,
	faWarehouse as falWarehouse,
	faInventory as falInventory,
	faAnalytics as falAnalytics,
	faShoppingBasket as falShoppingBasket,
	faCog as falCog,
	faReceipt as falReceipt,
	faInfoCircle as falInfoCircle,
	faSearch as falSearch,
	faChartLineDown as falChartLineDown,
	faTruck as falTruck,
	faRobot as falRobot,
	faComment as falComment,
	faScanner as falScanner,
	faFileEdit as falFileEdit,
	faArchive as falArchive,
} from '@fortawesome/pro-light-svg-icons';

import {
	faCheckCircle as fadCheckCircle,
	faExclamationCircle as fadExclamationCircle,
	faBoxAlt as fadBoxAlt,
} from '@fortawesome/pro-duotone-svg-icons';

library.add(
	// Custom
	farcQrCode,
	farcPositionReplacement,
	farcPositionDetach,
	falcReceiptsMissing,

	// Brands
	faVk,
	faInstagram,

	// Solid
	fasAngleLeft,
	fasAngleRight,
	fasAngleUp,
	fasAngleDown,
	fasHeart,
	fasComment,
	fasBullhorn,
	fasUserAlt,
	fasCheckSquare,
	fasWallet,
	fasPen,
	fasCircle,
	fasClock,
	fasRubleSign,
	fasCheckCircle,
	fasQuestionCircle,
	fasExclamationCircle,
	fasStore,

	// Regular
	farAngleLeft,
	farAngleRight,
	farAngleUp,
	farAngleDown,
	farTimes,
	farCalendar,
	farClipboard,
	farTrashAlt,
	farEye,
	farClone,
	farEllipsisH,
	farEllipsisV,
	farCheck,
	farCircle,
	farDotCircle,
	farSyncAlt,
	farPlus,
	farSquare,
	farExclamationCircle,
	farChevronDown,
	farChevronUp,
	farUndo,
	farArchive,
	farBoxAlt,
	farPen,
	farFolderPlus,
	farFolderMinus,
	farTruck,
	farCog,
	farTruckLoading,
	farCalendarEdit,
	farTrash,
	farComment,
	farInventory,
	farExternalLink,

	// Light
	falAngleLeft,
	falAngleRight,
	falAngleUp,
	falAngleDown,
	falTimes,
	falTimesCircle,
	falQuestionCircle,
	falExclamationCircle,
	falVideo,
	falPlus,
	falClipboardListCheck,
	falCheckCircle,
	falPlusCircle,
	falShippingTimed,
	falShoppingCart,
	falBagsShopping,
	falExternalLinkSquare,
	falUndo,
	falTachometer,
	falWarehouse,
	falInventory,
	falShoppingBasket,
	falAnalytics,
	falUsers,
	falCog,
	falReceipt,
	falInfoCircle,
	falSearch,
	falChartLineDown,
	falTruck,
	falRobot,
	falComment,
	falScanner,
	falFileEdit,
	falArchive,

	// Duotone
	fadCheckCircle,
	fadExclamationCircle,
	fadBoxAlt
);
