import { library } from '@fortawesome/fontawesome-svg-core';
import { faVk, faInstagram } from '@fortawesome/free-brands-svg-icons';

import {
	faAngleLeft as fasAngleLeft,
	faAngleRight as fasAngleRight,
	faAngleUp as fasAngleUp,
	faAngleDown as fasAngleDown,
	faHeart as fasHeart,
	faComment as fasComment,
	faBullhorn as fasBullhorn,
	faUserAlt as fasUserAlt,
	faCheckSquare as fasCheckSquare,
} from '@fortawesome/pro-solid-svg-icons';

import {
	faAngleLeft as farAngleLeft,
	faAngleRight as farAngleRight,
	faAngleUp as farAngleUp,
	faAngleDown as farAngleDown,
	faTimes as farTimes,
	faCalendar as farCalendar,
	faClipboard as farClipboard,
	faTrashAlt as farTrashAlt,
	faEye as farEye,
	faClone as farClone,
	faEllipsisH as farEllipsisH,
	faEllipsisV as farEllipsisV,
	faCheck as farCheck,
	faCircle as farCircle,
	faDotCircle as farDotCircle,
	faSyncAlt as farSyncAlt,
	faPlus as farPlus,
	faSquare as farSquare,
	faExclamationCircle as farExclamationCircle,
	faChevronDown as farChevronDown,
	faChevronUp as farChevronUp,
	faSearch as farSearch,
	faUndo as farUndo,
	faArchive as farArchive,
} from '@fortawesome/pro-regular-svg-icons';

import {
	faAngleLeft as falAngleLeft,
	faAngleRight as falAngleRight,
	faAngleUp as falAngleUp,
	faAngleDown as falAngleDown,
	faTimes as falTimes,
	faTimesCircle as falTimesCircle,
	faQuestionCircle as falQuestionCircle,
	faExclamationCircle as falExclamationCircle,
	faVideo as falVideo,
	faPlus as falPlus,
	faQrcode as falQrcode,
	faClipboardListCheck as falClipboardListCheck,
	faCheckCircle as falCheckCircle,
	faPlusCircle as falPlusCircle,
	faShippingTimed as falShippingTimed,
	faShoppingCart as falShoppingCart,
	faBagsShopping as falBagsShopping,
	faExternalLinkSquare as falExternalLinkSquare,
	faUndo as falUndo,
	faUsers as falUsers,
	faTachometer as falTachometer,
	faWarehouse as falWarehouse,
	faInventory as falInventory,
	faClipboardCheck as falClipboardCheck,
	faAnalytics as falAnalytics,
	faShoppingBasket as falShoppingBasket,
	faCog as falCog,
	faReceipt as falReceipt,
} from '@fortawesome/pro-light-svg-icons';

library.add(
	// Brands
	faVk,
	faInstagram,

	// Solid
	fasAngleLeft,
	fasAngleRight,
	fasAngleUp,
	fasAngleDown,
	fasHeart,
	fasComment,
	fasBullhorn,
	fasUserAlt,
	fasCheckSquare,

	// Regular
	farAngleLeft,
	farAngleRight,
	farAngleUp,
	farAngleDown,
	farTimes,
	farCalendar,
	farClipboard,
	farTrashAlt,
	farEye,
	farClone,
	farEllipsisH,
	farEllipsisV,
	farCheck,
	farCircle,
	farDotCircle,
	farSyncAlt,
	farPlus,
	farSquare,
	farExclamationCircle,
	farChevronDown,
	farChevronUp,
	farSearch,
	farUndo,
	farArchive,

	// Light
	falAngleLeft,
	falAngleRight,
	falAngleUp,
	falAngleDown,
	falTimes,
	falTimesCircle,
	falQuestionCircle,
	falExclamationCircle,
	falVideo,
	falPlus,
	falQrcode,
	falClipboardListCheck,
	falCheckCircle,
	falPlusCircle,
	falShippingTimed,
	falShoppingCart,
	falBagsShopping,
	falExternalLinkSquare,
	falUndo,
	falTachometer,
	falWarehouse,
	falInventory,
	falClipboardCheck,
	falShoppingBasket,
	falAnalytics,
	falUsers,
	falCog,
	falReceipt
);
